### ISSUE TITLE
Multi-cluster bug

### ISSUE THREAD

**Issue by laullon** [vmware/wavefront-adapter-for-istio#2]
**Describe the bug**
Metric doesn't have any tag to indicate from which Kubernates/Istio cluster came, so, a customer have the same application running on the two or more clusters metrics are mix and there is no way to know from which cluster came. 

**Expected behavior**
Metrics should have a tag, or source label, indicate from which cluster came.

**Steps to reproduce the bug**
Create 2 Istio cluster, deploy the same app on both, and deploy the adapter pointing to the same WF and with the same KEY.

**Comment by venilnoronha** [comment]
Fixed in #1.
