### ISSUE TITLE
How to send application metrics to Wavefront using ISTIO

### ISSUE THREAD

**Issue by piyushkumar13** [vmware/wavefront-adapter-for-istio#78]
Hi,
  My usecase is I have a spring boot project running in k8s with ISTIO setup. I want to send spring boot application metrics published at `/metrics` endpoint to wavefront using Istio. Prometheus provides a way to do this with some annotations as mentioned [here](https://preliminary.istio.io/faq/metrics-and-logs/#prometheus-application-metrics). Does wavefront with istio also provide a similar feature ? Please direct me how I can achieve sending my application metrics to wavefront.

**Comment by vikramraman** [comment]
@piyushkumar13 Wavefront provides a collector for Kubernetes that supports scraping prometheus metrics based on annotations.

See:
- https://github.com/wavefrontHQ/wavefront-kubernetes-collector
- https://github.com/wavefrontHQ/wavefront-kubernetes-collector/blob/v0.9.8/docs/discovery.md#annotations-based-discovery

Alternately, you can look into using a telegraf sidecar to achieve the same: https://github.com/wavefrontHQ/wavefront-kubernetes#usage-prometheus-scraping-over-a-kubernetes-service

**Comment by piyushkumar13** [comment]
@vikramraman Thanks for sharing. This was useful. It will work. 
However,
I have one more question - can the metrics from **envoy proxies collected by istio mixer** and  **application metrics**(from my service) directly pulled to wavefront proxy(similar to the way what prometheus does - it pulls all the metrics from mixer containing metrics from envoy proxy and application metrics based on [annotations](https://preliminary.istio.io/faq/metrics-and-logs/#prometheus-application-metrics).
I was exploring the option of [wavefront-adapter-for-istio](https://github.com/vmware/wavefront-adapter-for-istio). Would it suffice for what I my question about ?
